import { session } from 'electron';
import { extractSharedVideoUrl, videoLinkPlatform, type ResolvedDesktopVideoLink } from '../shared/video-link-resolver.ts';
import { resolveWithBundledChrome, type BrowserResolverCookie } from './chrome-video-resolver.ts';
import { downloadVideoForCopy } from './video-copy-download.ts';
import { resolveWechatVideo, resolveXhsVideo } from './social-video-parsers.ts';
import { resolvePublicWechatVideo } from './wechat-public-resolver.ts';

const RESOLVER_PARTITION = 'persist:aicut-video-resolver';
// A desktop UA keeps Douyin in its web player. A mobile UA makes the share
// page eagerly navigate to snssdk1128://, which Electron correctly refuses.
const DESKTOP_UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

async function settleNetworkConfiguration(operation: Promise<void>, label: string): Promise<void> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    await Promise.race([
      operation,
      new Promise<never>((_, reject) => {
        timer = setTimeout(() => reject(new Error(`${label} timed out`)), 10_000);
      }),
    ]);
  } catch (error) {
    // The default Electron session already follows system routing. A stalled network-service
    // acknowledgement must not prevent the independent bundled-Chrome resolver from running.
    console.warn(`[video-resolver] ${label}`, error instanceof Error ? error.message : error);
  } finally {
    if (timer) clearTimeout(timer);
  }
}

function cleanTitle(value: string, fallback: string): string {
  const title = value.replace(/\s*[-_|]\s*抖音\s*$/i, '').trim();
  return (title || fallback).replace(/[\\/:*?"<>|]/g, '_').slice(0, 160);
}

function extractDouyinVideoId(value: string): string {
  try {
    const parsed = new URL(value);
    const fromQuery = parsed.searchParams.get('group_id')
      ?? parsed.searchParams.get('modal_id')
      ?? parsed.searchParams.get('video_id');
    if (fromQuery && /^\d{8,24}$/.test(fromQuery)) return fromQuery;
    return /\/(?:video|detail)\/(\d{8,24})(?:\/|$)/.exec(parsed.pathname)?.[1] ?? '';
  } catch {
    return '';
  }
}

type ResolverCookie = BrowserResolverCookie | Awaited<ReturnType<Electron.Cookies['get']>>[number];

function netscapeCookies(cookies: readonly ResolverCookie[]): string {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by AI-cut local resolver; deleted after use.'];
  for (const cookie of cookies) {
    if (!cookie.name || !cookie.domain) continue;
    const domain = cookie.httpOnly ? `#HttpOnly_${cookie.domain}` : cookie.domain;
    const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = Math.floor(cookie.expirationDate ?? (Date.now() / 1000 + 3600));
    lines.push([domain, includeSubdomains, cookie.path || '/', secure, expires, cookie.name, cookie.value].join('\t'));
  }
  return `${lines.join('\n')}\n`;
}

/**
 * Douyin's 2026 share page no longer embeds playable metadata for a plain
 * server fetch. Let an isolated Chromium session execute Douyin's own page,
 * then capture the media request/currentSrc. The dedicated persistent
 * partition keeps Douyin's anti-bot bootstrap cookies between resolutions,
 * but never shares login cookies or browsing data with the editor.
 */
export async function resolveDesktopVideoLink(input: string): Promise<ResolvedDesktopVideoLink> {
  const shareUrl = extractSharedVideoUrl(input);
  if (!shareUrl) throw new Error('未找到有效的视频链接');
  const platform = videoLinkPlatform(shareUrl);
  if (platform === 'xiaohongshu' || platform === 'wechat') {
    const localSession = session.fromPartition(RESOLVER_PARTITION);
    const fetcher = (url: string, init?: RequestInit) => localSession.fetch(url, init);
    const media = platform === 'xiaohongshu'
      // Electron follows the user's system proxy (including Clash/V2Ray fake-IP routing). The
      // parser validates the final redirect target before reading the signed page state.
      ? await resolveXhsVideo(shareUrl, (url, init) => localSession.fetch(url, {
        ...init, redirect: 'follow',
      }))
      : await resolveWechatVideo(shareUrl, fetcher, (link) => resolvePublicWechatVideo(link, (url, init) => localSession.fetch(url, {
        ...init, redirect: 'follow',
      })));
    return downloadVideoForCopy(media.url, {
      name: media.name,
      referer: media.referer,
      decodeKey: media.decodeKey,
    });
  }
  if (platform !== 'douyin') return downloadVideoForCopy(shareUrl);

  const resolverSession = session.fromPartition(RESOLVER_PARTITION, { cache: true });
  // Use the operating system's routing rules. On machines using rule-based
  // clients (Clash/V2Ray), forcing `direct` bypasses their domestic-site rule
  // and Douyin's security bootstrap closes the connection.
  await settleNetworkConfiguration(resolverSession.setProxy({ mode: 'system' }), 'set system proxy');
  await settleNetworkConfiguration(resolverSession.closeAllConnections(), 'close stale connections');
  resolverSession.setUserAgent(DESKTOP_UA);
  // Resolve the ordinary HTTPS redirect before creating the page. This is
  // deterministic for current v.douyin.com links and avoids depending on the
  // optional snssdk1128:// app handoff firing inside a hidden window.
  const inputVideoId = extractDouyinVideoId(shareUrl);
  const redirectedUrl = inputVideoId ? shareUrl : await resolverSession.fetch(shareUrl, {
    redirect: 'follow',
    headers: { 'User-Agent': DESKTOP_UA },
    signal: AbortSignal.timeout(15_000),
  }).then((response) => response.url).catch(() => shareUrl);
  const redirectedVideoId = inputVideoId || extractDouyinVideoId(redirectedUrl);
  const initialUrl = redirectedVideoId
    ? `https://www.douyin.com/video/${encodeURIComponent(redirectedVideoId)}`
    : shareUrl;
  let browserCookies: readonly BrowserResolverCookie[] = [];
  try {
    const resolved = await resolveWithBundledChrome(initialUrl, redirectedVideoId);
    if (resolved.url) {
      return downloadVideoForCopy(resolved.url, {
        name: cleanTitle(resolved.title, '抖音视频'),
        referer: initialUrl,
        // Use yt-dlp's generic direct-URL downloader here. The URL was observed on the trusted
        // Douyin page, and this path follows system proxy routing without re-entering Douyin's
        // signed detail API or the fake-IP-sensitive server fetcher.
      });
    }
    browserCookies = resolved.cookies;
  } catch (error) {
    console.warn('[video-resolver] bundled Chrome fallback', error instanceof Error ? error.message : error);
  }
  // yt-dlp remains a second local extractor for platforms/pages it supports.
  // Only anonymous cookies from this dedicated partition are passed through;
  // AI-cut never reads the user's browser cookie store.
  try {
    const resolverCookies = await resolverSession.cookies.get({ domain: 'douyin.com' });
    const cookies = new Map<string, ResolverCookie>();
    for (const cookie of [...resolverCookies, ...browserCookies]) {
      cookies.set(`${cookie.domain}\t${cookie.path || '/'}\t${cookie.name}`, cookie);
    }
    return await downloadVideoForCopy(shareUrl, { cookies: netscapeCookies([...cookies.values()]) });
  } catch (error) {
    console.warn('[video-resolver] yt-dlp fallback', error instanceof Error ? error.message : error);
    throw new Error('无法在后台解析该视频链接；请确认链接对应的是公开视频后重试');
  }
}
